### ISSUE TITLE
Error on login after latest update

### ISSUE THREAD

**Issue by BradCOnGitHub** [SacredDuckwhale/Rarity#108]
Date: 2019-05-30 13:13:43
ID: 1
Error occured in: Global
Count: 1
Message: AceLocale-3.0: Rarity: Missing entry for 'Emerald Whelpling'
Debug:
   Rarity\Options_Defaults.lua:1724: PrepareDefaults()
   Rarity\Core.lua:553: DoEnable()
   Rarity\Core.lua:546:
      Rarity\Core.lua:545
   [C]: ?
   ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: ?
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:565: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1192:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AccelerandoVox, v1
  AllTheThings, v1.9.1a
  Altoholic, vr190
  AngryKeystones, v
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  AzeriteTooltip, v2.0.2
  BagBrother, v
  Bagnon, v8.1.9
  BagnonScrap, v8.1.0
  BattlePetBreedID, vr193
  BattlePetCount, v1.8.16
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  BigDebuffs, vv7.7
  BrokerCurrency, v8.1.0.1
  Capping, vv8.1.3
  CollectionShop, v3.07
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.26
  DBMCountPackHoTS, v1.6
  DBMCountPackOverwatch, v1.4.3
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DBMVPEnglishfemale, v8.1.11
  DBMVPEnglishmale, v8.1.11
  DeathNote, vr104
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ExRT, v4010
  GatherMate2, v1.43.6
  GoGoMount, v8.1.5
  HandyNotes, vv1.5.5
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesHallowsEnd, vv1.4.3
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLunarFestival, vv1.6.1
  HandyNotesWarfrontRares, v0.5.0
  Hekili, vv8.1.5-18
  iLvLr, v2.3.6
  InstanceAchievementTracker, v2.44.0
  IskarAssist, v
  KSpeedO, vr35
  MasterPlanA, vA
  MethodDungeonTools, v2.5.6
  MinimalArchaeology, v8.0.12.2
  NomiCakes, v8.0.0.1
  NPCScan, v8.0.1.13
  Overachiever, v1.0.5
  OverachieverCache, v1.0.5
  Paste, v1.4.10
  PersonalResourceDisplayNumbers, v1.0
  PetTracker, v8.1.2
  PetTrackerBreeds, v8.1.2
  PetTrackerSwitcher, v8.1.2
  PetTrackerUpgrades, v8.1.2
  Postal, vv3.6.0
  PremadeGroupsFilter, v1.27
  Quartz, v3.4.0
  QuartzProcs, v3.51
  RaidAchieveFilter, v2.0.2
  RaidAssist, v
  Rarity, v1.0 (r689-release)
  RarityOptions, v
  Rematch, v4.9.8
  ReputationBars, v8.0.0
  Scrap, v13.15
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TalkLess, v1.0.4
  tdBattlePetScript, v80100.01
  tdBattlePetScriptRematch, v80100.01
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TipTacTalents, v19.03.31
  TomCats, v1.0.11
  TomTom, vv80105-1.0.0
  TransmogTokens, v1.4.9
  WeakAuras, v2.12.3
  WorldQuestsList, v88
  YouOnlyHearOnce, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=bc0)

**Comment by SacredDuckwhale** [comment]
Whoops. That was an oversight and should be rectified in the second release.

**Comment by BradCOnGitHub** [comment]
That fixed it, thanks!
