### ISSUE TITLE
Progress bar not showing

### ISSUE THREAD

**Issue by TheAthenA714** [SacredDuckwhale/Rarity#123]
Hello !

So for a little while I've had a problem with Rarity, I'm not sure exactly when it appeared first but it was sometime after 8.2. Basically the progress bar isn't showing anymore, no matter what I do.

I've tried the usual, disabling every other add-on, new profile from scratch, completely fresh install, nothing worked.

So I went digging a little bit and I think I've figured the issue: in Core.lua, in the function UpdateBar() there's this line (3006) which checks the progress bar visibility:
` if not self.db.profile.bar.visible then self.barGroup:Hide() else self.barGroup:Show() end`
If I comment it out and replace it with just 
`self.barGroup:Show()`
then the progress bar shows up and works perfectly as intended, every option works.

The issue is that as far as I can tell, bar.visible is never set to true. Ever. Options_defaults.lua sets the default visibility at false (on line 217): 
```
bar = {
...
visible = false,
```
But nowhere in the code can I find a way to toggle that to true. 

So I've set the bar to always show as a workaround for now, but maybe there's a checkbox missing in the options to toggle bar.visible ?

**Comment by SacredDuckwhale** [comment]
The bar is toggled by clicking on the data object, which usually refers to an LDB icon.

Here is the code that toggles it, also found in Core.lua: https://github.com/SacredDuckwhale/Rarity/blob/master/Core.lua#L3168

**Comment by SacredDuckwhale** [comment]
I'll consider this resolved. Feel free to let me know if there's still a problem, though!
