### ISSUE TITLE
Great Sea Ray is no longer being tracked when fishing in the Tradewinds Market subzone

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#124]
Source: [WowAce](https://www.wowace.com/projects/rarity?comment=1922)

> Is Rarity no longer tracking the Great Sea Ray when fishing off the Tradewinds Market pier in Boralus Harbor? I just started leveling a new character and when I went to fish off the pier Rarity would not register when I caught something and add to the counter. I even logged out and onto another character and the add-on still did not increase the counter.

**Comment by SacredDuckwhale** [comment]
Fixed in 6f127b57494cbb4b03124b491fd99e7afd5877d7. Looks like the entirety of Boralus was overlooked when the item was first added.

**Comment by frodinii** [comment]
Same thing applies to Port of Zandalar, it doesn't seem to track any fishing attempts there

**Comment by SacredDuckwhale** [comment]
Good catch. Should work in every part of Dazar'alor (as of 71e23e73dc158b67bcad63305bdb0b93313db99f) and not just the very bottom.

This will be included in the next alpha, though I'm not pushing one for that change alone :)
