### ISSUE TITLE
Sha of Anger waypoint & Rukhmar correct waypoint

### ISSUE THREAD

**Issue by divinemaiden** [SacredDuckwhale/Rarity#131]
Hi There, I've modified on my side the correct waypoints for Sha of Anger (was missing) & Rukhmar (waypoint in hill commonly camped below spawn - was located at world boss icon which blizzard have in wrong spot)

		 ["Reins of the Heavenly Onyx Cloud Serpent"] =      { cat = MOP, type = MOUNT, method = BOSS, name = L["Reins of the Heavenly Onyx Cloud Serpent"], spellId = 127158, itemId = 87771, npcs = { 99999 }, tooltipNpcs = { 60491 }, questId = 32099, chance = 2000, equalOdds = true, statisticId = { 6989 }, enableCoin = true, worldBossFactionless = true, blackMarket = true, coords = { {m=379,x=53.7,y=64.7} }, },

		 ["Solar Spirehawk"] =                               { cat = WOD, type = MOUNT, method = BOSS, name = L["Solar Spirehawk"], spellId = 171828, itemId = 116771, npcs = { 99999 }, tooltipNpcs = { 87493, 83746 }, chance = 500, statisticId = { 9279 }, worldBossFactionless = true, questId = 37464, coords = { {m=542,x=34.98,y=38.65} }, },

**Comment by SacredDuckwhale** [comment]
Thanks! I've added it to the latest release.
