### ISSUE TITLE
Transparent main tooltip

### ISSUE THREAD

**Issue by Visqq** [SacredDuckwhale/Rarity#133]
![image](https://user-images.githubusercontent.com/42116056/64442158-9cdc4600-d0cf-11e9-8da1-6a29166c1e23.png)

Recently my main tooltip's background became transparent.
I don't see any option to even change that and it makes things really hard to read.

Is this a bug?
If not how can I undo that?

**Comment by SacredDuckwhale** [comment]
It's caused by another addon, as far as I know. ElvUI is known to cause this problem, but there may be others. Please try disabling everything but Rarity to make sure it can be reproduced as a first measure.

**Comment by Visqq** [comment]
After disabling ElvUI, the background is back to normal. But re-enabling ElvUI it's transparent again.
Is there any known setting in ElvUI that might causes this problem? I can't remember recent changes in the settings.

I'd like to keep my ElvUI, so I'm looking forward to hear from you, if any possible fixes exist.

**Comment by SacredDuckwhale** [comment]
I'm sorry, but I've never used ElvUI and this is definitely something you should report to the authors of that addon. If there is a fix or workaround I'm sure they would be the first to know.

**Comment by rodalpho** [comment]
Same problem here. Hopefully ElvUI can fix it!
