### ISSUE TITLE
Add Crimson Skipper

### ISSUE THREAD

**Issue by Urtgard** [SacredDuckwhale/Rarity#148]
The Crimson Skipper is missing in the database. https://www.wowhead.com/npc=158685

`["Crimson Skipper"] = {
	cat = BFA,
	type = PET,
	method = NPC,
	name = L["Crimson Skipper"],
	spellId = 309522,
	itemId = 172493,
	npcs = { 154154 },
	chance = 20,
	creatureId =158685,
	coords = {
		{ m = 942, x = 61.4, y = 16, n = L["Honey Smasher"] },
	},
},`

**Comment by SacredDuckwhale** [comment]
Thanks! Added in 0f3be0acdba1fc8e1d7a6f570150aae2b7b94cbc.

Side note: The key needs to be the item name and not the pet's, it won't be recognized properly otherwise.
