### ISSUE TITLE
Curse localization tool broken? Missing important localization

### ISSUE THREAD

**Issue by Urtgard** [SacredDuckwhale/Rarity#149]
I noticed tracking for the Sandclaw Nestseeker doesn't work. https://www.wowhead.com/item=169351

The german localization for "Glimmering Chest" is missing. It's "Glitzernde Truhe"

I tried to use the Curse Localization tool, but there isn't a entry for the chest.

**Comment by SacredDuckwhale** [comment]
Hm, looks like I forgot to add the latest phrases! Or perhaps CurseForge didn't properly add them, I've no idea.

Either way, the English phrases should now be updated, thanks for the reminder!

**Comment by SacredDuckwhale** [comment]
I've manually updated everything once again, hopefully the detection is now working.

It would be useful to do this task automatically (via CI or otherwise), so I've created https://github.com/SacredDuckwhale/Rarity/issues/150 and am closing this issue as resolved :)
