### ISSUE TITLE
Review zone IDs for Skyshards to make sure the 8.3 vale is covered

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#153]
I actually found one in the daily mini-vision, at Shrine of the Seven Stars. This zone at least wasn't covered, and there might be more.

**Comment by nickbayley** [comment]
I had a quick look today. Seems `1570` is the map ID that corresponds with the mini vision where you looted a Skyshard.

https://wow.tools/maps/worldmap.php?id=1570&bc=b8a03ea551a7bbcee507b1838064792c

I didn't find any others. It seems `1530` (BFA Vale) uses the same map ID, regardless of where the corruption is.

**Comment by SacredDuckwhale** [comment]
Neat! I was mostly thinking about stuff like Guo-Lai Halls, but I just checked and it doesn't seem to have a separate ``mapID``.

The only thing I'd want to check before resolving this: Does the Horde version of the Vision use a different map? ``1570`` clearly is the Alliance version.

I can't really look into this as it's currently the Uldum week, but soon (tomorrow) this will change so I suppose I shouldn't forget :)

**Comment by SacredDuckwhale** [comment]
For what it's worth, I added the missing zone in 6c73c7cfc0425a258bb9e671fcedfda969825a76.

**Comment by nickbayley** [comment]
Just checked the lesser vision on my horde character. It is the same place.

![image](https://user-images.githubusercontent.com/2527831/110606649-4d724c80-8182-11eb-98d4-67952afc57f5.png)

**Comment by SacredDuckwhale** [comment]
Thanks! Time to close this issue, then.
