### ISSUE TITLE
Add track for items need for : Going to need a bigger bag

### ISSUE THREAD

**Issue by formigao** [SacredDuckwhale/Rarity#179]
can we have rarity tracking those items ?

**Comment by SacredDuckwhale** [comment]
Sure, but aren't some of those items very specific (i.e., not toys/mounts/pets)? I don't know if adding them to the addon's core database would be very helpful, especially since you can just add them manually via the Custom tab.

The actual collectibles should already be tracked by default.

**Comment by godejord** [comment]
I double-checked just to be sure, but all the toys/pets/mounts criteria for this achievement are already implemented in the database. The other items are indeed just random items and consumables.

**Comment by SacredDuckwhale** [comment]
Very good, thanks for looking into this :)
