### ISSUE TITLE
Tusks of Mannoroth

### ISSUE THREAD

**Issue by BaturalNoobs** [SacredDuckwhale/Rarity#180]
I'm running r697 and am unable to track Tusks of Mannoroth. When I kill Garrosh I don't get a Rarity message about the Tusks. Here's my Custom tab settings:

- Method of obtaining: Drops from a boss requiring a group.
- Type of item: Toy or item
- Item ID: 112935
- NPCs: 71865

Options (selected):

- Track this
- Announce

Attempts:

- Attempts: 30
- Chance: 3000
- Enable coins: Selected

Instance Difficulty (Selected):

- 10-player Raid instance (legacy content; not flexible)
- 25-player Raid instance (legacy content; not flexible)
- 10-player Heroic Raid instance (legacy content, not flexible)
- 25-player Heroic Raid instance (legacy content, not flexible)
- Normal Raid (10-30 players)
- Heroic Raid (10-30 players)
- Mythic Raid (20 players)

Disable for classes:

- Druid
- Mage
- Rogue
- Warlock
- Demon Hunter
- Hunter
- Monk
- Priest
- Shaman

Here's the export:

Azq9Af8CaqLykiheE8lMJWo2opui/FJVdZvCYap2KvbCbon9lPRTpGEifit1GWkokRosyHAlHRRqGymOIZwjqhaqLKVisZCWU+mhEp6iHlP0nDBRVaZKmkwq06UuUuoqJZ6R6DpJbSSi80pksxCnVfko4CsRfCbBNIFGkqpvJDSaJONVVU6Kapyq0jVSukeUVhKhtaqKZYIaBCr4NTUEKiZMoIJ7aaXgvNoZ2KCt2jrwpcxg0ouOu6mxtsAkYN0TPkpSye0uSC8EKlhvmWo7OLCTBiw2DpzFARsHlnZymysOLCF2ltOFDA782Vk6estU28GBP8eSfzhwlo4MDsz6OIsHhwaT25S6LcR4g4ID3nW3UFlDekqSwnSpN8C+mxprC4wyAb+mRq7DEERYXqkFvyLaF5N+LxJ5pprsRwUqRoPDEFocRonDEBocJojDaHEYIohDg4s3KLiqhZSwhnbEGsp8KdvdrQKX1RSoGAKjSPxqtGiwqfLFpBhlkiRg+rdut3FgWnyUpIv9Cg6NBounUHyrXQp2JPOw9BeUS+UkJlNaIS/m/wFPLCsLjqofqcNo5BXR/wI=

Any ideas how to get this fixed so it tracks Tusks?

**Comment by SacredDuckwhale** [comment]
It looks like this item only drops from Mythic difficulty, so presumably that's the one you were doing? If so, this ``25-player heroic raid instance (legacy content, not flexible)`` isn't the right setting as it refers to the 25HC raids from the WOTLK/Cataclysm era (I think).

Rarity won't track attempts for items with a difficulty setting unless you're actually in an instance of the correct difficulty.

**Comment by BaturalNoobs** [comment]
@SacredDuckwhale Thanks for your reply. I also appreciate all your hard work on the add on - it’s amazing.

The Tusks drop in both Heroic ([source](https://www.wowhead.com/item=112935/tusks-of-mannoroth&bonus=448#comments:id=2536721)) and Mythic. I’m running Siege of Orgrimmar on Heroic because you can repeatedly run it and bonus roll after each kill ([via this method](https://www.wowhead.com/item=112935/tusks-of-mannoroth&bonus=448#comments:id=2867265)). Here are the five different versions of the item:

**Warforged**
https://www.wowhead.com/item=112935

The other four item IDs say “This item's source is no longer available/removed” on Wowhead:

**Heroic**
https://www.wowhead.com/item=103785

**Heroic Warforged**
https://www.wowhead.com/item=105393

**Mythic**
https://www.wowhead.com/item=104646

**Mythic Warforged**
https://www.wowhead.com/item=105642

Any idea how I can track this on heroic kills? Thanks again!
