### ISSUE TITLE
When using the PetTracker addon, redundant information is displayed in the tooltip for battle pets

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#195]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/422)
> Both Rarity and Pettracker add "Drop" and "Zone" information to caged pets tooltip. Having both enabled will cause tooltip to display same information twice like this:

**Comment by nickbayley** [comment]
I couldn't reproduce this. 

I did find this from the same user who reported: https://github.com/Jaliborc/PetTracker/issues/210

**Comment by SacredDuckwhale** [comment]
Pretty sure the text is from Blizzard's pet journal. Multiple addons adding stuff to the ``GameTooltip`` is always problematic, though it depends on what they're adding (and how). If there isn't another report of this problem, I doubt it's something we need to be concerned about if it isn't currently reproducible.

I love when problems just solve themselves without me having to do anything. Thanks!
