### ISSUE TITLE
Update the addon to account for Shadowlands API changes

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#198]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/418)

Will have to check the PTR, and hope externals are updated already?

**Comment by Goutye** [comment]
As of Today (Pre-patch release on retail servers), Rarity does not work for the reasons stated in the comment above.
To fix the issue, the following page should help (Backdrop fix)
https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes

**Comment by SacredDuckwhale** [comment]
Hopefully most errors should be fixed; I'll leave this open for now since there may be more to be discovered.

**Comment by rodalpho** [comment]
Downloaded the ZIP from github; the LDB icon shows up but nothing else works. Nothing shows on mouseover and /rarity doesn't work. Also the rarity_options addon needs to be updated as well.

One small additional note, the SL pre-patch interface version for the TOC is actually 90001, not 90000.

**Comment by SacredDuckwhale** [comment]
That doesn't sound right; everything's working for me locally. You probably need to update LibQTip and potentially any of the other dependencies. They're usually packaged by Curse and as such not part of this repository.

Thanks for the notice, I've updated the interface version once more. What exactly is the issue with the options module, though?

**Comment by rodalpho** [comment]
Updating libqtip worked!

The options module interface version was still 80300, it just needs to be updated also.

**Comment by Lagicrus** [comment]
Version: 698 
Seems like on load there is an issue with the backdrop on the bars?

![image](https://user-images.githubusercontent.com/24227350/96355545-9a259000-10da-11eb-92fa-f97eafc76997.png)

**Comment by SacredDuckwhale** [comment]
Old versions won't work in the Shadowlands prepatch. Since uploads on Curse are currently broken, please try the (temporary) link at the top here: https://www.curseforge.com/wow/addons/rarity

**Comment by Lagicrus** [comment]
> Old versions won't work in the Shadowlands prepatch. Since uploads on Curse are currently broken, please try the (temporary) link at the top here: https://www.curseforge.com/wow/addons/rarity

Ah thanks, I think I have seen Details having the same issue? So they just released a "Details - Shadowlands" and just kept updating that instead. I'll try and get that zip working. Thanks

**Comment by SacredDuckwhale** [comment]
The issue is now fixed and the latest release available on Curse again.

I'm still leaving this open since I didn't have time to go through the entire list of changes yet and may have missed some.

**Comment by Lagicrus** [comment]
> The issue is now fixed and the latest release available on Curse again.
> 
> I'm still leaving this open since I didn't have time to go through the entire list of changes yet and may have missed some.

Just got it via Curse 👌 
If I find any issues I will drop a comment, thanks a bunch

**Comment by SacredDuckwhale** [comment]
Considering this done; if there are any obscure changes I missed they'll have to be fixed separately.
