### ISSUE TITLE
Add toys obtainable from Vixx the Collector

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#204]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/426)

IIRC testing this will be a PITA because it's a rare spawn. I think I looked into it before.

**Comment by FuxieDK** [comment]
I made these, when I was farming the items...

Azf5Av8CapWq1xRqNpKbKsUvlcg3KXaK9sJuKvtVSj9VEsMQfiO6TTKUQgarQsNVdVBSnknpmFTnVKmFVLVUJWkxRZZL4iEFPUUtk3hONJECU1VMpsp05aIqsQ0pdVm4TtBGVdRWVdJmAttVgvMqqdOkPiMl31UqjwmNk6TRkmo8Up2kqGlIcU0VuacKVqqE1qpEHaY0Og5YL5TEQbYNDjicNVHhwQTe9Q+w+bzcgFWsTnrgNDIEU1autoX6k0gCbOzIOwcf7KwK8Kum08F2C/UnkQUsIIXOgw/WTs46MQy0QKBFITUdEgdZ4CNLCx8Duy9KHGRH9tJUqwUDi3XrxEC24KB/sjL4YL1QZg/Zn8q7WjAkDYEDDvonK4MPpqxcbQv1J5EN2NiRdw4+mCJFY5+UMq0K8Kum028fV4/bR0OSokIcWQELtPMkDrLjgJ1QITt45CxV20L9SWQDnlaBbMEjZ6mjVSBbsN1C/Ulkg2HgaRXIFuy+KHGQHdlLU60WDCzWrRMDSRusF8rsIftTSxA04HDWRIUHE3jXP8Dm83IDVrE66YHTyBBcCUvVtlB/EtmAR85Sz9p5EtnBAlLoPPhg7eSsE8NACwRaFFLTIXGQ/Q0TsrTwkQU+BnZWBfiCphewZxcSB1mIQnSCoMEBT6tAdrDdQv1JZMeQhSgE8S4tDnhaBbKD7RbqTyI7hixEIYh3b3DA0yqQHWy3UH8S2TEMTFm5o1UgW7DdQv1JZINhYKlpOTthJcBXn83FyIDm/sr9RSLdaJmdeOly7eEBbBJqykM2RMH/Ag==

**Comment by SacredDuckwhale** [comment]
Added in 8443171dc29b98e15e594c0f841676c06da0539a.
