### ISSUE TITLE
Shadowlands bugs: Dump

### ISSUE THREAD

**Issue by Lagicrus** [SacredDuckwhale/Rarity#205]
Version: 698 on Twitch
When running `/rarity dump` I get an error instead as logged below

![image](https://user-images.githubusercontent.com/24227350/96355485-153a7680-10da-11eb-94dd-0200d1e940e8.png)

**Comment by SacredDuckwhale** [comment]
I'm not getting this error, but I've pushed a change in37bbe6369f2bbd1c269d2e2d7b24d421b86c3bfe that hopefully fixes it for you.

Since Curse is still broken you'll have to download it manually for now (or just replace the Utils/PrettyPrint file from GitHub) ;/

**Comment by SacredDuckwhale** [comment]
The latest release, now available on Curse, should include this fix.
