### ISSUE TITLE
Add tracking for Hallow Items from Handful of Treats

### ISSUE THREAD

**Issue by Lagicrus** [SacredDuckwhale/Rarity#206]
As the title says add tracking for hallow items that drop from the item [Handful of Treats](https://www.wowhead.com/item=37586/handful-of-treats#contains) 
Such as the

- [Hallowed Helm](https://www.wowhead.com/item=33292/hallowed-helm#contained-in-item)
- [Sinister Squashling](https://www.wowhead.com/item=33154/sinister-squashling)

I don't think the rest need to be tracked

**Comment by SacredDuckwhale** [comment]
These seem more like items you might want to add as a "custom" item yourself.

Rarity doesn't track appearances and the pet is incredibly common, which means most people won't really care about tracking it.

**Comment by Lagicrus** [comment]
Fair enough 👍 I will look into that, thanks
