### ISSUE TITLE
Minimap Icon Hover Request

### ISSUE THREAD

**Issue by chillface** [SacredDuckwhale/Rarity#207]
Any chance there can be an option to change the minimap icon to be clickable instead of hovering over to show the Rarity information? Theres been many times I have hovered over it accidentally and my farming list information fills my screen. Would love to have it only display when i click it if possible.

**Comment by SacredDuckwhale** [comment]
If I understand you correctly, this is a duplicate of https://github.com/SacredDuckwhale/Rarity/issues/197

**Comment by chillface** [comment]
yes exactly, sorry i didnt see that one posted already!
