### ISSUE TITLE
Outdated information for LibQTip in the pkgmeta file

### ISSUE THREAD

**Issue by laric** [SacredDuckwhale/Rarity#210]
Could the reason why you can't upload to curse be that your pkgmeta is in error for libqtip?

https://repos.wowace.com/wow/libqtip-1-0

`    Libs/LibQTip-1.0:
        url: https://repos.wowace.com/wow/libqtip-1-0
        tag: latest
`

Seems to work. It is not in subversion any longer. Moved to git.

**Comment by SacredDuckwhale** [comment]
Good catch! It appears this was indeed the problem.

**Comment by SacredDuckwhale** [comment]
Should be fixed as of af9be299c29cfd3e18f7cf18eca52ccf27cd2c74.
