### ISSUE TITLE
Add Shadowlands collectibles to the item database

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#216]
Roadmap:

- [x] Create shadowlands content category (needs icon?)
- [x] Mounts
  - [x] Drops
    - [x] https://www.wowhead.com/item=184167/mawsworn-soulhunter
    - [x] https://www.wowhead.com/item=180461/horrid-dredwing#comments
    - [x] https://www.wowhead.com/item=181819/marrowfangs-reins#comments (also M+?)
    - [x] https://www.wowhead.com/item=182080/predatory-plagueroc
    - [x] https://www.wowhead.com/item=182083/bonecleavers-skullboar#comments
    - [x] https://www.wowhead.com/item=180582/endmire-flyer-tether
    - [x] https://www.wowhead.com/item=182085/blisterback-bloodtusk
    - [x] https://www.wowhead.com/item=182084/gorespine
    - [x] https://www.wowhead.com/item=182079/slime-covered-reins-of-the-hulking-deathroc
    - [x] https://www.wowhead.com/item=181815/armored-bonehoof-tauralus#comments
    - [x] https://www.wowhead.com/item=182075/bonehoof-tauralus
    - [x] https://www.wowhead.com/item=180730/wild-glimmerfur-prowler
    - [x] https://www.wowhead.com/item=181818/chewed-reins-of-the-callow-flayedwing
    - [x] https://www.wowhead.com/item=184062/gnawed-reins-of-the-battle-bound-warhound
    - [x] https://www.wowhead.com/item=184160/bulbous-necroray
    - [x] https://www.wowhead.com/item=184162/pestilent-necroray
    - [x] https://www.wowhead.com/item=184161/infested-necroray
  - [x] Paragon
    - [x] https://www.wowhead.com/item=182081/reins-of-the-colossal-slaughterclaw
    - [x] https://www.wowhead.com/item=183800/amber-ardenmoth
- [x] Pets
  - [x] Drops
    - [x] https://www.wowhead.com/item=183395/pommel-jewel-of-remornia
    - [x] https://www.wowhead.com/item=181266/feasting-larva
    - [x] https://www.wowhead.com/item=181267/writhing-spine
    - [x] https://www.wowhead.com/item=181283/foulwing-buzzer
    - [x] https://www.wowhead.com/item=183410/sharpclaw
    - [x] https://www.wowhead.com/item=184397/lost-featherling
    - [x] https://www.wowhead.com/item=180584/blushing-spiderling
    - [x] https://www.wowhead.com/item=180869/devoured-wader
    - [x] https://www.wowhead.com/item=181172/boneweave-hatchling
    - [x] https://www.wowhead.com/item=183623/spinemaw-gormling
    - [x] https://www.wowhead.com/item=180588/bucket-of-primordial-sludge
    - [x] https://www.wowhead.com/item=180591/vial-of-roiling-emotions
    - [x] https://www.wowhead.com/item=180587/animated-tome
    - [x] https://www.wowhead.com/item=181270/invertebrate-oil
    - [x] https://www.wowhead.com/item=180585/bottled-up-rage
    - [x] https://www.wowhead.com/item=183408/undying-deathroach
    - [x] https://www.wowhead.com/item=181263/shy-melvin
    - [x] https://www.wowhead.com/item=181265/corpselouse-larva
    - [x] https://www.wowhead.com/item=183192/frenzied-mawrat
    - [x] https://www.wowhead.com/item=183194/maw-stalker
    - [x] https://www.wowhead.com/item=183116/hissing-deathroach
    - [x] https://www.wowhead.com/item=183409/decaying-mawrat
    - [x] https://www.wowhead.com/item=183117/severs
    - [x] https://www.wowhead.com/item=183407/contained-essence-of-dread
    - [x] https://www.wowhead.com/item=180586/lightbinders
    - [x] https://www.wowhead.com/item=180602/crimson-dredwing-pup
    - [x] https://www.wowhead.com/item=181271/sludge-feeler
    - [x] https://www.wowhead.com/item=183191/maw-crawler
    - [x] https://www.wowhead.com/item=183115/tower-deathroach
    - [x] https://www.wowhead.com/item=183193/jar-of-ashes
    - [x] https://www.wowhead.com/item=183195/torghast-lurker
  - [x] Paragon
    - [x] https://www.wowhead.com/item=181269/micromancers-mystical-cowl
    - [x] https://www.wowhead.com/item=184399/larion-cub
    - [x] https://www.wowhead.com/item=180635/hungry-burrower
    - [x] https://www.wowhead.com/item=180601/stonewing-dredwing-pup
- [x] Toys
  - [x] Drops
    - [x] https://www.wowhead.com/item=184312/borr-geths-fiery-brimstone
    - [x] https://www.wowhead.com/item=184292/ancient-elethium-coin
    - [x] https://www.wowhead.com/item=181794/oropheas-lyre
    - [x] https://www.wowhead.com/item=180873/smolderheart
    - [x] https://www.wowhead.com/item=184476/regenerating-slime-vial
    - [x] https://www.wowhead.com/item=184418/acrobatic-steward
    - [x] https://www.wowhead.com/item=184404/ever-abundant-hearth
    - [x] https://www.wowhead.com/item=184415/soothing-vesper
    - [x] https://www.wowhead.com/item=184413/mnemonic-attunement-pane
  - [x] Paragon
    - [x] https://www.wowhead.com/item=184396/malfunctioning-goliath-gauntlet
    - [x] https://www.wowhead.com/item=184495/infested-arachnid-casing
    - [x] https://www.wowhead.com/item=184435/mark-of-purity

**Comment by SacredDuckwhale** [comment]
It appears lots of those are a 100% drop. Since there's no wowhead data yet, I guess that means waiting until it's known which ones are actually rare...

**Comment by theleblol** [comment]
Arboreal Gulper and Spinemaw gladechewer mounts are most definitely 100% drop.

**Comment by SacredDuckwhale** [comment]
Added with ef4dfd9d8e0a727194c0667d1eedcae7254158ba.
