### ISSUE TITLE
Add support for Shadowlands bonus roll currency

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#222]
Only if it can actually be used to obtain collectibles?

**Comment by godejord** [comment]
[No new bonus rolls in Shadowlands](https://www.wowhead.com/news=318109/bonus-rolls-do-not-exist-for-shadowlands-content)

**Comment by SacredDuckwhale** [comment]
Thanks, I guess that makes sense.
