### ISSUE TITLE
Add support for Shadowlands archaeology races

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#223]
There are new ones, are there not?

**Comment by godejord** [comment]
Can [confirm](https://www.wowhead.com/news=316850/archaeology-is-not-expected-to-receive-updates-in-shadowlands) archaeology is **not** a thing in Shadowlands.

**Comment by SacredDuckwhale** [comment]
Very well, nothing to do here then.
