### ISSUE TITLE
Add defeat detection for the Mawsworm Soulhunter (Gorged Shadehound)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#227]
Source: https://github.com/SacredDuckwhale/Rarity/pull/225

Item: https://www.wowhead.com/item=184167/mawsworn-soulhunter#comments

I haven't unlocked this area. In fact, I don't have anything unlocked. But someone who has could find out the quest ID using this addon: https://www.curseforge.com/wow/addons/questschanged

**Comment by nickbayley** [comment]
I killed the Gorged Shadehound a few minutes ago. Here is the quest ID that the addon showed: `63433`

![image](https://user-images.githubusercontent.com/2527831/102549443-02312c00-40b4-11eb-8fb6-5a88cf81ad05.png)

**Comment by SacredDuckwhale** [comment]
Thanks! Added in 12f834e7ddb1571788f572669dcabfc593676f65.
