### ISSUE TITLE
Screenshots are taken even if the setting to take them is turned OFF (?)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#256]
Source: [WowAce](https://www.wowace.com/projects/rarity?comment=2581)
> I have screenshots turned off, but for some reason it keep taking them on achievement gains.

Will have to see if I can reproduce it.

**Comment by godejord** [comment]
I have tried to reproduce this, but have been unable to get the reported results. I only tried with custom items, but seems to work perfectly on my end.

**Comment by SacredDuckwhale** [comment]
That's pretty much what I expected. It sounds like it would be difficult to reproduce without additional information.

I'll see if I can reproduce it when I have some time, and if I can't I'll just close it until there's additional reports of the same problem.

**Comment by SacredDuckwhale** [comment]
Can confirm this problem is **not** reproducible on my end. If anything, the user might have issues with specific items/settings that we can't troubleshoot without additional information.
