### ISSUE TITLE
Options is missing a Content Category for Shadowlands

### ISSUE THREAD

**Issue by godejord** [SacredDuckwhale/Rarity#273]
The Rarity Options is missing a separate content category for Shadowlands. These categories are implemented for all previous expansions, but the Shadowlands one is missing. This results in players being unable to filter out Shadowlands items from the tooltip

**Comment by godejord** [comment]
Closing this issue because I am retarded. The category was implemented in the modules just fine, it's just my side that hadn't updated the Rarity_Options separate folder with the new files.

**Comment by SacredDuckwhale** [comment]
Yup, the category was part of https://github.com/SacredDuckwhale/Rarity/issues/216 (first checkbox). This time I didn't forget!
