### ISSUE TITLE
Announcements in public channels are no longer functioning while outdoors (?)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#275]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/466)

Probably related to some API changes made by Blizzard. I recall them limiting the ``SendChatMessage`` API to limit spam, but I never followed up on this after testing it briefly. Back then announcements were working, but it's possible they're limited only under certain circumstances?

**Comment by godejord** [comment]
There are more details about this problem here #134.

**Comment by SacredDuckwhale** [comment]
I didn't misremember then, I just forgot I already created an issue earlier. I don't think there's anything we could do to enable the announcements given Blizzard's restrictions.

We could try not sending any messages in those channels, but AFAIK it's all handled by the `LibSink`` library and I don't know if we can modify this feature easily with how it's currently implemented.

That said, this is a duplicate so I'll close it.
