### ISSUE TITLE
Add tracking for Lucy's Lost Collar

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#276]
Source: [Curse](https://www.wowace.com/projects/rarity?comment=2604)

https://www.wowhead.com/npc=175390/dirty-glinting-object apparently has a chance to drop a [pet](https://www.wowhead.com/item=184507/lucys-lost-collar), but is only available during a specific world quest.

**Comment by nickbayley** [comment]
A bit of extra info on this one.

It is only available when:

1. You have a Training in Revendreth/Bastion/Ardenweald/Maldraxxus or Training Our Forces calling active. Training Our Forces appears when the current Training in >Zone< matches your covenant. For example, if you are Venthyr and Training in Revendreth is up, it will be named Training Our Forces for you.
2. And then it is also dependent on the trainee that spawns for you. The ones you are after for each covenant is as follows:
    - Drippy for Venthyr
    - Twinklewings for Night Fae
    - Deos for Kyrian
    - Dregs for Necrolord

Dirty Glinting Object can be looted multiple times per day. 

I think it will be able to be implemented as a simple NPC loot check.

**Comment by nickbayley** [comment]
Had a chance to test this today, and doesn't work as I was thinking. Seems @godejord has it covered though :)
