### ISSUE TITLE
Add holiday-style reminder when Mawsworn Soulhunter is available

### ISSUE THREAD

**Issue by godejord** [SacredDuckwhale/Rarity#285]
The [Mawsworn Soulhunter](https://www.wowhead.com/item=184167/mawsworn-soulhunter) mount is only available when [Gorged Shadehound](https://www.wowhead.com/npc=174861/gorged-shadehound) can spawn in The Maw. This NPC is tied to the "Hunt: Shadehounds", which is on a rotation with 3 other "Hunts". I'm not sure there is even an easy way to track this ingame, apart from the icon that pops on the zone map. Either way would be nice looking into

**Comment by SacredDuckwhale** [comment]
Holiday reminders use the ingame calendar. I doubt there's any way this would be useful for tracking rotations unrelated to the calendar API :(

**Comment by SacredDuckwhale** [comment]
I think I'll just close this; I don't see any way we could track arbitrary events that don't come with an API. Hopefully, tracking the quest completion via Defeat Detection will allow people who are actively farming this to be reminded of when the event resets.

If anyone knows how this event functions in detail we can look into it once more :)
