### ISSUE TITLE
Review holiday items to make sure they're using the proper holiday texture (for calendar-based notification)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#289]
In reviewing the item database, I've noticed that there's a lot of holiday items that don't appear to have their ``holidayTexture`` set (e.g., Big Love Rocket). If I understand the logic correctly, this would imply there won't be any calendar-based notification for them.

This means their holiday reminders wouldn't be working as intended. Not sure if this was changed when Blizzard moved to different reward structures (e.g., container instead of normal loot), so that's something that might need to be investigated first.

**Comment by godejord** [comment]
I just realized after pushing the update that I didn't come across Big Love Rocket at all. Perhaps I have gone blind, but I cannot seem to find that mount. Did it get lost in the refactoring?

**Comment by nickbayley** [comment]
Seems here: https://github.com/SacredDuckwhale/Rarity/commit/0a69210c92058c6655341d33280d1989059a2633

I guess because of the large diffs, the search feature of GitHub doesn't pick up on it.

**Comment by SacredDuckwhale** [comment]
Can confirm it went AWL. I must've somehow messed up copy/pasting it in. I guess that's why I'm wary of refactoring without tests :(

Looking into if there's any others I missed currently, but it's tricky to tell with just the diffs. I've tried writing some scripts but they're telling me the number of items is the same, which can't really be true, so I'm still trying to figure this one out.

**Comment by SacredDuckwhale** [comment]
Done; the results can be found in a temporary debug branch (https://github.com/SacredDuckwhale/Rarity/tree/debug-db-refactoring), and the result is easily visualized in this commit: https://github.com/SacredDuckwhale/Rarity/commit/028512912397eac55d4a39b7434c8497fb36a27b

This simulates the changes made to the database (in terms of item keys only); as we can see only the Big Love Rocket went missing, so that's a relief :D

**Comment by SacredDuckwhale** [comment]
Since we can now be reasonably sure nothing else is missing, I've added the Big Love Rocket again in 7dcf605a97e0f7e2c4c3b65039d707aeb6198749.
