### ISSUE TITLE
Rarity r638

### ISSUE THREAD

**Issue by sgkdnay** [SacredDuckwhale/Rarity#31]
As prepatch came out, been stuck at "Loading (0%)" and when I open interface, it shows "Unable to retrieve item information from the server".  Error msg:

```
1x Rarity\Core.lua:4093: attempt to call global 'CalendarGetDate' (a nil value)
Rarity\Core.lua:4093: in function `ScanCalendar'
Rarity\Core.lua:4029: in function `ScanExistingItems'
Rarity\Core.lua:499: in function `DoEnable'
Rarity\Core.lua:451: in function <Rarity\Core.lua:450>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...s\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: ?
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:488: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1189: in function <FrameXML\UIParent.lua:1085>

Locals:
nil
```

**Comment by SacredDuckwhale** [comment]
Yes, I'm working on fixing the addon as we speak. In fact, unless I missed something I should be done.

Try the newest alpha versions from Curse! It'll be a while before I can in good conscience tag them as "release" :)

**Comment by sgkdnay** [comment]
I'll get that checked out :)  Will keep ya posted

**Comment by sgkdnay** [comment]
Btw the other error in Options_Defaults.lua are all incorrect for m=xxx (mapId), Bliz has changed all the zone, instance, raid into new ID's.  I can see that it will be a ONE giant headache :(

**Comment by SacredDuckwhale** [comment]
Yes, it's a giant mess. I'm working on sorting it out, but it'll take a while!

I'm closing this as resolved, though.
