### ISSUE TITLE
Lib missing

### ISSUE THREAD

**Issue by Elbryan01** [SacredDuckwhale/Rarity#37]
been getting this error

3x Rarity\Core.lua:1: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "LibSink-2.0".
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:220: in function `EmbedLibrary'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:202: in function `EmbedLibraries'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:169: in function `NewAddon'
Rarity\Core.lua:1: in main chunk

Locals:
(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "LibSink-2.0"."

and if I install LibSink-2.0 I get 

1x Rarity\Core.lua:1: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceBucket-3.0".
[C]: ?
...acePostal\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:220: in function `EmbedLibrary'
...acePostal\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:202: in function `EmbedLibraries'
...acePostal\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:169: in function `NewAddon'
Rarity\Core.lua:1: in main chunk

Locals:
(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceBucket-3.0"."

**Comment by SacredDuckwhale** [comment]
Curse apparently has an issue and is packaging standalone versions of various libraries, instead of their embedded ones. Again. Or maybe they're

I was going to change the TOC embed paths to account for this, but I think it is easier to just hope they fix it ASAP. I'll see how it goes and maybe do change them if it takes too long...

You can simply drag the libraries from their respective folders to where they SHOULD be (one level below that, presumably). so that the path matches what is written in Rarity.toc.

**Comment by SacredDuckwhale** [comment]
Can I just ask, what version were you using? I tried to narrow down where things may have changed and I can't see anything wrong with the libraries in any of the versions I checked.

Oddly enough, the libraries you posted about seem to be embedded correctly. I also am not getting any error when using the releases downloaded directly from Curseforge.

**Comment by Elbryan01** [comment]
it was with the last alpha version alpha version r664-alpha-nolib.

Just tried it with a new char with only buggrabber and the relase version of rarity(r641) installed and i get these errors

2x ...rfaceRarity\Libs\LibBars-1.0\LibBars-1.0.lua:4: attempt to index global 'LibStub' (a nil value)
...rfaceRarity\Libs\LibBars-1.0\LibBars-1.0.lua:4: in main chunk

Locals:
MAJOR = "LibBars-1.0"
MINOR = 90024
(*temporary) = nil
(*temporary) = nil
(*temporary) = "%d+"
(*temporary) = "24"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'LibStub' (a nil value)"

----

2x Rarity\Locales.lua:2: attempt to call global 'LibStub' (a nil value)
Rarity\Locales.lua:2: in main chunk

Locals:
L = nil
(*temporary) = nil
(*temporary) = "AceLocale-3.0"
(*temporary) = "attempt to call global 'LibStub' (a nil value)"

---

2x Rarity\Core.lua:1: attempt to call global 'LibStub' (a nil value)
Rarity\Core.lua:1: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "AceAddon-3.0"
(*temporary) = "attempt to call global 'LibStub' (a nil value)"

---

86x (null)

**Comment by SacredDuckwhale** [comment]
> r664-alpha-nolib

Are you aware what a "nolib" version is? It means there are no embedded libraries included, and you'll have to install them separately. If you install the regular version or add the required libraries manually, there shouldn't be any errors.

**Comment by SacredDuckwhale** [comment]
Closing this as invalid, as it won't be an issue when using full release version that includes embedded libraries.
