### ISSUE TITLE
Statistics-based attempts counting in Mythic Keystone dungeons isn't working (for some dungeons?)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#68]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/327)
> currently on the newest update .681 and I am unable to get the mythic + cache to count towards the mounts for the 3 dungeons that drop the mounts. doing them the first time on mythic is counting, but any times after while doing mythic plus is now.

See #52 - apparently it doesn't work?

**Update: According to some users, the Mythic Plus runs aren't increasing the ingame statistics, and therefore Rarity is not adding any attempts for the mounts.**

In my somewhat limited testing, as well as according to another user who ran the dungeons without encountering any problems, **this problem could not be reproduced.**

*This means I can't fix it for the affected users unless I somehow manage to find out what's wrong.*

My only idea would be running all the dungeons on regular mythic as well as mythic plus difficulty, with a character of each faction, multiple times, and see if the tracking ever breaks. I don't have the means nor the time to do that currently.

**Comment by SacredDuckwhale** [comment]
Okay, now that I've some more insight I can say... it is broken but it still works.

The statistics provided by Blizzard don't differentiate between regular Mythic and Mythic Keystone runs. This causes a host of potential issues, but as a side effect the tracking MOSTLY works unless one of many things goes wrong.

I've added a list to the top, so that the issues may be tackled later on.

**Comment by SacredDuckwhale** [comment]
It appears the statistics are no longer tracking mythic keystone runs, according to several user reports. Maybe they used to and BLizzard fixed the "bug" - who knows?

This means that the keystone detection should be re-added ASAP, and that the statistics tracking can remain for regular mythic difficulty.

**Comment by SacredDuckwhale** [comment]
I'm just going to edit in the tests because something is clearly wrong, but I can't yet tell what it is.

---

| Dungeon | Level | Faction | Statistics Detection | Challenge Mode Detection | 
| ---------- | -- | ----------- | -- | ----- |
| Freehold | 2 | Alliance | Working | Unknown (Game crashed...)

**Comment by SacredDuckwhale** [comment]
https://www.wowace.com/projects/rarity?comment=303

It's probably best to test King's Rest and The Underrot as Horde, specifically. Maybe there's something broken on Blizzard's end and those statistics aren't working for some dungeons, or not for Horde players anyway.

**Comment by SacredDuckwhale** [comment]
https://www.curseforge.com/wow/addons/rarity?comment=1519
>  Hi, would it be possible to fix attempts detection for KR & Underrot mounts on Mythic+ ? they all work in mythic 0 but only sharkbait works for Mythic+ actually

Not sure if this is a Horde-specific problem, Blizzard has simply broken the statistics for these dungeons, or something else might be awry. No way around testing manually, I think..

**Comment by Hemario** [comment]
It seems that we're using a different Opening spell when it comes to opening Challenger's Cache.
Debugging information for Underrot +7 on Horde side:

```
Rarity: Debug mode ON 
Rarity: Detected UNIT_SPELLCAST_SENT for unit = player, spellID = 115008, castGUID = Cast-3-3769-1841-11352-109132-00001CB09F, target = nil 
Rarity: Detected UNIT_SPELLCAST_SENT for unit = player, spellID = 6247, castGUID = Cast-3-3769-1841-11352-6247-00001CB0A1, target = Challenger's Cache 
Rarity: LOOT_READY with target: NO TARGET 
Rarity: Locking session for 1 second(s) to prevent duplicate attempts from being counted 
Rarity: LOOT_READY with target: NO TARGET 
Rarity: Session is locked; ignoring this LOOT_READY event 
Rarity: Unlocking session to continue scanning for new LOOT_READY events 
You receive item: [Glowing Azerite Crystal]. 
[Heart of Azeroth] gains 250 Artifact Power. 
Rarity: BAG_UPDATE 
Rarity: Setting lastNode to nil 
Rarity: Setting lastNode to nil 
Dump: value=GetSpellInfo(6247) 
[1]="Opening", 
[3]=134237, 
[4]=0, 
[5]=0, 
[6]=5, 
[7]=6247 
```

**Comment by SacredDuckwhale** [comment]
I can't look into Mythic plus as it requires extensive testing, and I lack the time. This'll have to wait :(

**Comment by SacredDuckwhale** [comment]
I believe this is now fixed, at least for FH, UR and KR. I've run all those dungeons and never had an issue with the statistics not being counted, on both Alliance and Horde.

The only problem remaining would be Mechagon, as no statistics exist for this dungeon. But that's a different issue: https://github.com/SacredDuckwhale/Rarity/issues/170
