### ISSUE TITLE
Set Skyshards to be tracked repeatedly by default

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#80]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/312)

This seems like a simple issue, but there isn't a way to do this currently. One could add an exception for this item, but I'd rather be able to set items as repeatable arbitrarily so future updates can build on it, e.g., by allowing all pets to be tracked repeatedly etc.

**Comment by godejord** [comment]
Shouldn't it be enough to just set the item to `repeatable = true`?
As far as I can tell this setting will only make Rarity re-enable tracking on the item if it is found, so shouldn't really affect anything else.

**Comment by SacredDuckwhale** [comment]
You're right, this does seem to work. Fixed in a9fbb1e408c4f61f835b3a42ba2036d6a928513c.
