### ISSUE TITLE
Tracking for Mimiron's Head (still) broken after the changes to Ulduar's difficulty (?)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#93]
Source: [Curse](https://www.curseforge.com/wow/addons/rarity?comment=1509)
> Just killed Yogg-Saron in Ulduar-there was no loot on the body, just a chest at the entrance to his room.  Checking Wowhead, all loot now shows up in the chest including Mim's Head (as of 8.0 according to a poster.).  Rarity didn't do an attempt annouce when I killed Yogg nor when I opened the chest.

After looking into the code, I suspect the original workaround (#11) may not have covered this item, as I didn't fully understand the various methods of detection after having just taken over maintenance of the addon. I did add an encounter-based detection for the pet, but clearly the mount wasn't covered by this (and I never noticed).

A detection routine based on looting the corpse is out of the question,since it's no longer possible now that there is a chest containing the loot instead. The statistics don't count kills for the new difficulty (flexible 10-25) either, so that's why the mount probably isn't tracked.

**Comment by godejord** [comment]
I did a run of Ulduar to check if this was an actual problem or not. Given the popularity of this mount, I would expect there to be way more reports if this was an ongoing issue. Nevertheless, I killed the boss normally and I did get an attempt tracked for the mount. Adding a [screenshot](https://imgur.com/a/eOBDCaT) to verify it. Neither of the Yogg-Saron statistics were updated though.

**Comment by SacredDuckwhale** [comment]
Looking at the git history, the detection method wasn't changed since at least the transition to Git (from SVN). So if it did break at some point in between, it must've been because of something Blizzard did (and presumably fixed, later). That's not unheard of, I suppose.

Since there haven't been any reports (that I can recall) similar to this one, I'll close it as not reproducible. Thanks for testing!
