### ISSUE TITLE
Add toy drops from Vixx the Collector (Seat of the Triumvirate)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#94]
Items:
* https://www.wowhead.com/item=153004/unstable-portal-emitter#comments
* https://www.wowhead.com/item=152982/vixxs-chest-of-tricks

See also: https://www.wowhead.com/npc=127882/vixx-the-collector

**Comment by godejord** [comment]
These items are already in the database, so this issue can safely be closed.

**Comment by SacredDuckwhale** [comment]
Confirmed duplicate of https://github.com/SacredDuckwhale/Rarity/issues/204. Guess I lost track and/or forgot to search the issues before creating that one.
