### ISSUE TITLE
Black Temple difficulty seems to be flexible now and pet tracking may be affected (?)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#96]
I didn't pay much attention, but it seems to be similar to Ulduar now. Will have to test and verify later.

**Comment by godejord** [comment]
I just ran a full Black Temple to test this, and I can confirm that the tracking still works for all 6 pets.
-Leviathan Egg
-Shard of Supremus
-Fragment of Anger
-Fragment of Desire
-Fragment of Suffering
-Sultry Grimoire

Can safely close this issue.

**Comment by SacredDuckwhale** [comment]
Yeah, those use the ``NPC`` method and as such should be fine. Only kill statistics should be affected by the Timewalking difficulty change, and I suppose TBC raids didn't have those to begin with. The exception is https://www.wowhead.com/achievement=1089/illidan-stormrage-kills-the-black-temple which must've been added retroactively, but if there isn't a collectible drop from that boss it doesn't really matter.
